/*
 * photocell.h
 *
 *  Created on: 2023/07/11
 *      Author: RATTAN
 */

#ifndef PERIPHERAL_LIB_GANWEI_8BIT_PHOTOCELL_PHOTOCELL_H_
#define PERIPHERAL_LIB_GANWEI_8BIT_PHOTOCELL_PHOTOCELL_H_



#endif /* PERIPHERAL_LIB_GANWEI_8BIT_PHOTOCELL_PHOTOCELL_H_ */
